
modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]

modId="reservermod"
version="${file.jarVersion}"

displayName="Reserver Mod"

#logoFile="examplemod.png"

credits=""
authors=""

description=''''''
[[dependencies.reservermod]]

    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.reservermod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"